### ISSUE TITLE
Please bump actions/core to 1.10.0 to fix warning

### ISSUE THREAD

**Issue by jepler** [carlosperate/arm-none-eabi-gcc-action#29]
CircuitPython builds (e.g., https://github.com/adafruit/circuitpython/actions/runs/3236398936/jobs/5302249039#step:5:23) are saying

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

That doc gives the following fix:

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Comment by carlosperate** [comment]
Thanks @jepler! I'll update and push a new release 👍

**Comment by carlosperate** [comment]
Alright, [v1.5.2](https://github.com/carlosperate/arm-none-eabi-gcc-action/releases/tag/v1.5.2) has been released, and the `v1` tag moved to point to that 🚢

**Comment by jepler** [comment]
We appreciate it, thank you.
