### ISSUE TITLE
Dwarf registers mapping

### ISSUE THREAD

**Issue by valdemar-const** [carlosperate/arm-none-eabi-gcc-action#33]
Sorry, I do not know where to ask this question. In Dwarf info produced by gcc what mean registers numbers? Where to find dwarf reg numbers mapping on hardware registers?

**Comment by carlosperate** [comment]
Hi @valdemar-const, have you been able to resolve your query?
This is probably not the best place to ask about general embedded dev questions, but if you are looking for register info the microcontroller datasheet is the best place to find that. If you are looking for Arm register info, then the Arm Technical Reference Manual for Cortex-M will be have that info.

**Comment by carlosperate** [comment]
I'll close this as off-topic.
