### ISSUE TITLE
Should we add the 12.2.MPACBTI-Rel1 beta release?

### ISSUE THREAD

**Issue by carlosperate** [carlosperate/arm-none-eabi-gcc-action#36]
The latest official release (already in this action) is `12.2.Rel1`. The new `12.2.MPACBTI-Rel1` has this as their "what's new":

> This release supports the Cortex-M85 processor, and provides Beta support for the Cortex-M PACBTI extension. This release only includes the arm-none-eabi toolchain triplet. Toolchains described as [Beta] have not had the same level of testing as the other toolchains.

More on PACBTI: https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/armv8-1-m-pointer-authentication-and-branch-target-identification-extension

The previous PACBTI beta release was `12.2.MPACBTI-Bet1` released in September, which wasn't added to this action. Looks like this will be officially supported in the next 12.2 (or higher) official release.

If anybody needs the release please add a coment here and I'll be happy to add it, but in the meantime it might not be required for the majority of users of this Action.

**Comment by mbrossard** [comment]
Probably obsolete issue now that 12.3.Rel1 is out (#42)

**Comment by carlosperate** [comment]
Yes, thanks! 12.3.Rel1 released: https://github.com/carlosperate/arm-none-eabi-gcc-action/releases/tag/v1.7.0
