### ISSUE TITLE
Add Version 12.3.Rel1

### ISSUE THREAD

**Issue by mbrossard** [carlosperate/arm-none-eabi-gcc-action#42]
Latest on https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads is
```
Arm GNU Toolchain
Version 12.3.Rel1
Released: July 28, 2023
```

**Comment by carlosperate** [comment]
Thanks Mathias! Completely missed it.
I've got a PR ready and should be updating the Action inminently:
- https://github.com/carlosperate/arm-none-eabi-gcc-action/pull/43

**Comment by carlosperate** [comment]
Released in https://github.com/carlosperate/arm-none-eabi-gcc-action/releases/tag/v1.7.0, thanks!
