### ISSUE TITLE
Update to Node.20 js

### ISSUE THREAD

**Issue by dhalbert** [carlosperate/arm-none-eabi-gcc-action#49]
GitHub Actions is transitioning to Node.js 20. See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/. Most `github/actions` actions have had a major version bump to accomodate this, e.g.: https://github.com/actions/checkout/pull/1436

**Comment by carlosperate** [comment]
Thanks @dhalbert!
And thanks to @amyspark this has been updated in v1.8.1 (and the v1 tag updated):
https://github.com/carlosperate/arm-none-eabi-gcc-action/releases/tag/v1.8.1
