### ISSUE TITLE
2 minute hang after install & caching

### ISSUE THREAD

**Issue by Crzyrndm** [carlosperate/arm-none-eabi-gcc-action#51]
https://github.com/actions/toolkit/issues/1643
~90s of logged activity then stuck for 2 minutes. ^^ issue suggests calling process.exit as a workaround
![image](https://github.com/carlosperate/arm-none-eabi-gcc-action/assets/8765278/87615781-12d8-43e4-a0c0-89fb25ba6852)

**Comment by carlosperate** [comment]
Just to confirm, the log shown in the screenshot seems to run correctly (although there seems to be a cache miss) and after that last log entry it waits for 2min without doing anything else? what is the next log entry after that? is it the next workflow job step?

Is the cache actually saved successfully? Can you see it in repo caches? https://github.com/<username>/<project>/actions/caches

**Comment by Crzyrndm** [comment]
* The hang only happens on a cache miss
* It caches successfully
* After 2 minutes it continues to the next workflow step. There is no further log entry for this step

**Comment by meisZWFLZ** [comment]
I am also experiencing this issue:
[here](https://github.com/LemLib/Gamepad/actions/runs/9215638572/job/25354390993#step:4:69)
![image](https://github.com/carlosperate/arm-none-eabi-gcc-action/assets/80860310/ada00f5c-f948-40d9-83cb-98d0df9a0418)
and [here](https://github.com/LemLib/Gamepad/actions/runs/9215638760/job/25354391559?pr=4#step:4:68)
![image](https://github.com/carlosperate/arm-none-eabi-gcc-action/assets/80860310/5a7273c3-3871-47c7-9895-4e4bc0548cce)

In my case the cache was also sucessful.

The actual step running this action: [action.yml](https://github.com/LemLib/pros-build/blob/e0f3251974c2f5b044b8e5d8665db7cfcb5dfad7/action.yml#L65C1-L68C30)
release: `10-2020-q4`

**Comment by carlosperate** [comment]
Thanks for the confirmation of the issue @Crzyrndm and the additional info @Crzyrndm.

I've been able to replicate the same behaviour (~2min hangs on cache misses, without anything happening after the last log entry during that time) and it seems to be resolved by updating the @actions/cache dependency to the latest version (in hopes that a PR like https://github.com/actions/cache/pull/1217 might have fixed it).

In the same environment were I was able to easily replicate the issue it seems to be resolved when using [carlosperate/arm-none-eabi-gcc-action@v1.8.2](https://github.com/carlosperate/arm-none-eabi-gcc-action/releases/tag/v1.8.2). @Crzyrndm @meisZWFLZ could you try the latest release and check if it has been fixed on your CI runs as well? Thanks!

**Comment by Crzyrndm** [comment]
This is working for me. Thanks for the fix @carlosperate
